package reporters

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestHTMLReporterWrite(t *testing.T) {
	dir := t.TempDir()

	s := Stats{
		Name:            "html-test",
		TotalRequests:   100,
		Successful:      90,
		Failed:          10,
		TPS:             50.0,
		TotalDuration:   2 * time.Second,
		LatencyMin:      1.0,
		LatencyMean:     20.0,
		LatencyMedian:   18.0,
		LatencyP90:      40.0,
		LatencyP95:      60.0,
		LatencyP99:      100.0,
		LatencyMax:      200.0,
		LatencyStdDev:   15.0,
		StatusCodeBreakdown: map[int]int64{200: 80, 500: 10},
		Histogram: map[string]int64{
			"<10ms":  30,
			"10-50ms": 50,
			">50ms":  20,
		},
	}

	r := NewHTMLReporter(dir)
	if err := r.Write(s); err != nil {
		t.Fatal(err)
	}

	filename := filepath.Join(dir, "report.html")
	data, err := os.ReadFile(filename)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "Stress Test Report") {
		t.Error("missing title")
	}
	if !strings.Contains(content, "html-test") {
		t.Error("missing test name")
	}
	if !strings.Contains(content, "Total Requests") {
		t.Error("missing total requests")
	}
	if !strings.Contains(content, "Latency Percentiles") {
		t.Error("missing latency section")
	}
	if !strings.Contains(content, "Status Codes") {
		t.Error("missing status codes")
	}
	if !strings.Contains(content, "200") {
		t.Error("missing status code 200")
	}
	if !strings.Contains(content, "Latency Histogram") {
		t.Error("missing histogram")
	}
	if !strings.Contains(content, "Generated by stress-test-utils") {
		t.Error("missing footer")
	}
}

func TestHTMLReporterNoOutputDir(t *testing.T) {
	s := Stats{TotalRequests: 10}
	r := NewHTMLReporter("")
	// Should create in current directory; skip since we don't know CWD
	_ = s
	_ = r
}

func TestStatusRows(t *testing.T) {
	breakdown := map[int]int64{200: 80, 500: 20}
	rows := statusRows(breakdown, 100)
	if len(rows) != 2 {
		t.Fatalf("expected 2 rows, got %d", len(rows))
	}
	// Check pct is computed
	for _, row := range rows {
		if row.Pct < 0 || row.Pct > 100 {
			t.Errorf("invalid percentage %f for code %d", row.Pct, row.Code)
		}
	}
}

func TestHistogramRows(t *testing.T) {
	buckets := map[string]int64{"<10ms": 30, "10-50ms": 50, ">50ms": 20}
	rows := histogramRows(buckets, 100)
	if len(rows) != 3 {
		t.Fatalf("expected 3 rows, got %d", len(rows))
	}
}
